schema,table,rls_enabled,rls_forced
auth,audit_log_entries,true,false
auth,flow_state,true,false
auth,identities,true,false
auth,instances,true,false
auth,mfa_amr_claims,true,false
auth,mfa_challenges,true,false
auth,mfa_factors,true,false
auth,oauth_clients,false,false
auth,one_time_tokens,true,false
auth,refresh_tokens,true,false
auth,saml_providers,true,false
auth,saml_relay_states,true,false
auth,schema_migrations,true,false
auth,sessions,true,false
auth,sso_domains,true,false
auth,sso_providers,true,false
auth,users,true,false
cron,job,true,false
cron,job_run_details,true,false
public,claims,true,false
public,event_members,true,false
public,events,true,false
public,items,true,false
public,list_exclusions,true,false
public,list_recipients,true,false
public,list_viewers,true,false
public,lists,true,false
public,profiles,true,false
public,user_plans,true,false
realtime,messages_2025_09_25,false,false
realtime,messages_2025_09_26,false,false
realtime,messages_2025_09_27,false,false
realtime,messages_2025_09_28,false,false
realtime,messages_2025_09_29,false,false
realtime,messages_2025_09_30,false,false
realtime,messages_2025_10_01,false,false
realtime,messages_2025_10_02,false,false
realtime,messages_2025_10_03,false,false
realtime,schema_migrations,false,false
realtime,subscription,false,false
storage,buckets,true,false
storage,buckets_analytics,true,false
storage,migrations,true,false
storage,objects,true,false
storage,prefixes,true,false
storage,s3_multipart_uploads,true,false
storage,s3_multipart_uploads_parts,true,false
supabase_migrations,schema_migrations,false,false
supabase_migrations,seed_files,false,false
vault,secrets,false,false